# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicho',
            name='categoria',
        ),
        migrations.AddField(
            model_name='dicho',
            name='categoria',
            field=models.ManyToManyField(to='api.Categoria'),
        ),
    ]
